config/routes.rb
BackChannelV1::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy, :index]
  resources :posts#, :only => [:new, :create]

  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/newreply', :to => 'posts#newreply'
  match '/showvote', :to => 'votes#show'
  match '/newvote',  :to => 'votes#new'
  match '/removepost',  :to => 'posts#delete'
  match '/newadmin',    :to => 'users#newadmin'
  match '/removeuser',  :to => 'users#delete'
  match '/search',      :to => 'posts#search'
  match '/help',        :to => 'pages#help'

  root :to => 'sessions#new'

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  has_many :posts, :dependent => :destroy

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true,
                    :length   => { :maximum => 50 },
                    :uniqueness => { :case_sensitive => false }

  validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }

  validates :account_type, :presence => true

# Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    return nil  if user.nil?
    return user if user.salt == cookie_salt
  end


  private

    def encrypt_password
      if self.encrypted_password.nil?
        self.salt = make_salt #unless has_password?(password)
        self.encrypted_password = encrypt(password) #password is local not in db
      end
    end
    
    def encrypt(string)
      secure_hash("#{self.salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]

  def index
    @all_users = User.all(:order => 'users.total_votes DESC')
    @title = "All Users"
    flash.now[:info] = "This is privileged information to be viewed by Admin only!"
  end


  def new
    @user  = User.new
    @title = "Sign Up"
    @acc_type = "regular"
    if(params[:user_type] == "guest")
      sign_in create_guest_user
      # save it in the cookie
      flash[:info] = "Welcome to the BackChannel App!"
      redirect_to posts_path and return
    else
      render 'new'
    end
  end


  def create

    if params[:user_type_admin] == "admin"
      @admin_user = User.new(params[:user])
      @admin_user.account_type = "admin"
      @admin_user.total_votes  = 0
      if @admin_user.save
        flash[:info] = "Successfully created Admin account."
      else
        flash[:error] = "Could not create Admin account"
      end
      @title = "All Users"
      redirect_to users_path and return
    end

    @user = User.new(params[:user])
    @user.total_votes = 0

    if params[:user_type_from_button] == "admin"
      @user.account_type = "admin"
    else
      @user.account_type = "regular"
    end

    if @user.save
      sign_in @user
      flash[:info] = "Welcome to BackChannel App!"
      redirect_to posts_path
    else
      @title = "Sign up"
      render 'new'
    end
  end



  def newadmin
    @user  = User.new
    @acc_type = "admin"
    @title = "Sign Up"
    render 'new'
  end

  def delete
    @user = User.find(params[:user_id])

    Post.find_all_by_user_id(@user.id).each do |post|
      # delete all entries in votes table with post_id = this
      votes = Vote.find_all_by_post_id(post.id)
      votes.each do |v|
        v.destroy
      end

      # destroy all replies to this post
      replies = Post.find_all_by_parent(post.id)

      replies.each do |r|
        # destroy all votes to this reply
        votes = Vote.find_all_by_post_id(r.id)
        votes.each do |v|
          v.destroy
        end
        r.destroy
      end

      post.destroy
    end

    if(@user.id == current_user.id) # then sign him out and delete user
      sign_out
      @user.destroy
      redirect_to signin_path and return
    end

    @user.destroy
    flash[:info] = "User and all his votes/posts have been destroyed"
    redirect_to users_path
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper

  def create_guest_user
      user = User.new
      user.id    = -1
      user.name  = "Guest User"
      user.email = "guest@guest.com"
      user.account_type  = "guest"
      user.encrypted_password = "dummyvalue"
      user.salt = "dummyvalue"
      return user
  end

end

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if current_user.nil? %>
    <div class="flash error">You do not have permissions to access this page!</div>
    <%= link_to "Back to Posts Homepage", posts_path %>
<% elsif current_user.account_type != "admin" %>
    <div class="flash error">You do not have permissions to access this page!</div>
    <%= link_to "Back to Posts Homepage", posts_path %>
<% else %>

    <h2>List of all Users</h2>

    <%= link_to "Create new Admin Account", newadmin_path, :class => "hyperlink round" %>
    <br/>

    <table border="1" class="manage_accounts_table" >
      <tr>
        <b>
        <td><b>User Name</b></td>
        <td><b>Email</b></td>
        <td><b>Account Type</b></td>
        <td><b>Total Posts authored</b></td>
        <td><b>Total Replies authored</b></td>
        <td><b>Total Votes received</b></td>
        <td ><b>Action</b></td>
        </b>
      </tr>
      <% @all_users.each do |each_user| %>
          <tr >
            <td><%= each_user.name %></td>
            <td><%= each_user.email %></td>
            <td><%= each_user.account_type.capitalize %></td>
            <td><%= all_posts = Post.find_all_by_user_id_and_parent(each_user.id, -1).count %>
              <%= link_to "View Posts", search_path(:searched_from => "admin_console", :search_type => "user", :search_string => each_user.name), :class => "view_posts_admin round" %></td>
            <td><%= total_replies_authored(each_user.id, all_posts) %></td>
            <td><%= each_user.total_votes%></td>
            <td ><%= link_to "Delete User", removeuser_path(:user_id => each_user.id), :confirm => "Are you sure?", :class => "delete_user_admin round"  %></td>
          </tr >

      <% end  %>
    </table>

<% end  %>

app/views/users/new.html.erb
<% if @acc_type == "admin" && current_user.nil? %>
    <div class="flash error">You do not have permissions to access this page!</div>
    <%= link_to "Back to Homepage", root_path %>
<% elsif @acc_type == "admin" && current_user.account_type != "admin" %>
    <div class="flash error">You do not have permissions to access this page!</div>
    <%= link_to "Back to Posts Homepage", posts_path %>
<% else%>

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', :object => f.object %>
        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.text_field :email %>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation, "Re-enter Password" %><br />
          <%= f.password_field :password_confirmation %>
        </div>

        <div>
          <% if User.find_all_by_account_type("admin").count == 0 %>
              <%= radio_button_tag :user_type_from_button, "admin" %> Create an Admin Account
          <% elsif @acc_type == "admin" %>
              <%= hidden_field_tag :user_type_admin, "admin" %>
          <% end %>
        </div>

        <br />

        <% if @acc_type == "admin" %>
            <div class="actions">
              <%= f.submit "Create Admin", :class => "main_signin" %>
              <%= link_to "Cancel", posts_path, :class => "cancel_admin round" %>
            </div>
        <% else%>
            <div class="actions">
              <%= f.submit "Sign up", :class => "main_signin" %>
              <%= link_to "Cancel", root_path, :class => "cancel_admin round" %>
            </div>
        <% end %>
    <% end %>
<% end %>