config/routes.rb
BackChannelV1::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy, :index]
  resources :posts#, :only => [:new, :create]

  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/newreply', :to => 'posts#newreply'
  match '/showvote', :to => 'votes#show'
  match '/newvote',  :to => 'votes#new'
  match '/removepost',  :to => 'posts#delete'
  match '/newadmin',    :to => 'users#newadmin'
  match '/removeuser',  :to => 'users#delete'
  match '/search',      :to => 'posts#search'
  match '/help',        :to => 'pages#help'

  root :to => 'sessions#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
#  attr_accessor :parent#:content#, :parent, :user_id
#  attr_accessible :content#, :parent#, :user_id

  belongs_to :user

  validates :content, :presence => true, :length => { :within => 2..240 }

  validates :user_id, :presence => true

  validates :weight, :presence => true

#  default_scope :order => 'posts.created_at DESC',
#                :limit => 100

  public

#    def set_parent(id)
#      self.parent = id
#    end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  def index
    @title = "All Posts"
  end


  def new
    @title = "New Post"
    @post = Post.new
    @parent_id = -1
  end

  def newreply
    @title = "New Reply"
    @post = Post.new
    @parent_id = params[:parentid]
    render 'new'
  end

  def create
    @title = "All Posts"

    if params[:post][:content].empty?
      flash[:error] = "Content cannot be empty!"
      redirect_to posts_path and return
    end

    @post = Post.new
    @post = current_user.posts.build(params[:post])
    @post.parent = params[:parentid]

    if(@post.parent == -1)
      @post.weight = Post.find_all_by_parent(-1).count
    else
      @post.weight = 0
    end

    if @post.save
      flash[:info]  = "Successfully Posted!"
    else
      flash[:error] = "Unsuccessful attempt. Try Again."
    end
    redirect_to posts_path
  end

  def delete
    @title = "All Posts"
    @post = Post.find(params[:post_id])
    # delete all entries in votes table with post_id = this
    votes = Vote.find_all_by_post_id(@post.id)
    votes.each do |v|
      v.destroy
    end

    # destroy all replies to this post
    replies = Post.find_all_by_parent(@post.id)

    replies.each do |r|
      # destroy all votes to this reply
      votes = Vote.find_all_by_post_id(r.id)
      votes.each do |v|
        v.destroy
      end
      r.destroy
    end

    flash.now[:info] = "Post Deleted!"
    @post.destroy
    render 'index'
  end

  def show
    @title = "All Posts"
    render 'index'
  end


  def search
    @title = "Search Results"
    if params[:search_string].blank?
      flash[:error] = "Cannot have an empty Search Field!"
      redirect_to posts_path and return
    end
    @searched_from = params[:searched_from]

    if params[:search_type] == "user"
      search_str = params[:search_string].strip
      @author  = User.all( :conditions => ["users.name LIKE ?", search_str])[0]
      #@author = author_arr[0]
      #author_obj.each do |each_author|
      #  if each_author.name.casecmp(params[:search_type])
      #    @author = each_author
      #  end
      #end

      if(@author.nil?)
        @post_threads  = Array.new
        @reply_threads = Array.new
        render 'posts/searchresult' and return
      end

      @post_threads = Post.find_all_by_user_id_and_parent(@author.id, -1)

      post_thread_ids = Array.new
      @post_threads.each do |post|
        post_thread_ids << post.id
      end

      replies =  Post.find_all_by_user_id(@author.id, :conditions => ["posts.parent >= ?",1])
      @reply_threads = Array.new

      replies.each do |r|
        @reply_threads << r.parent
      end
      @reply_threads.uniq

      @reply_threads -= post_thread_ids
      @search_type = "user"
      @search_string = params[:search_string]

      render 'posts/searchresult' and return

    elsif params[:search_type] == "posts"
      search_str = params[:search_string].strip.downcase
      @post_threads  = Array.new
      @reply_threads = Array.new # contains only the post ids of reply threads

      Post.find_all_by_parent(-1).each do |each_post|
        if(each_post.content.downcase.include?(search_str))
          @post_threads << each_post
        end
      end

      Post.all(:conditions => ["posts.parent >= ?",1]).each do |each_reply|
        if(each_reply.content.downcase.include?(search_str))
          @reply_threads << each_reply.parent
        end
      end
      @reply_threads.uniq
      @search_type = "posts"
      @search_string = params[:search_string]

      render 'posts/searchresult' and return
    end

  end

end

app/helpers/posts_helper.rb
module PostsHelper


  def display_parent(p)
    if p.parent==-1
     "--"
    elsif p.parent.nil?
     "Some problem: It is nil"
    else
      p.parent.to_s
    end
  end

  def total_replies_authored(id, all_posts)
    #upper_limit = 1.0/0
    Post.find_all_by_user_id(id,:conditions => ["posts.parent >= ?",0]).count# - all_posts
  end

end

app/views/posts/index.html.erb
<% if current_user.nil? %>
    <div class="flash error">Please Sign In or Browse as a Guest User to view this page.</div>
    <%= link_to "Back to Homepage", root_path %>
<% else %>

    <b class ="search">SEARCH:</b>
    <%= form_for(:post, :url => search_path) do |f| %>
        <div class="field">
          <%= render 'shared/error_messages', :object => f.object %>

          <%= text_field_tag :search_string %>
          <div>
            <%= radio_button_tag :search_type, "user", :checked => true %> Search by Author
            <%= radio_button_tag :search_type, "posts" %> Search by Posts
          </div>
        </div>

        <div class="actions">
          <%= f.submit "Search", :class => "main_signin" %>
        </div>
    <% end %>

    <br />


    <h1 class = "all_posts round"> All Posts </h1>

    <% if current_user.account_type !="guest" %>
        <%= link_to "New Post", new_post_path, :class =>  "newpost round" %><br />
    <% end %>

    <% Post.find_all_by_parent(-1, :order => 'posts.weight DESC').each do |p| %>
        <div class = "c6 round">
          <div class = "c4">

            <div class="votes vc1" >
              <% if current_user.account_type != "guest" %>
                  <b> <%= link_to" #{Vote.find_all_by_post_id(p.id).count} Votes",
                                 newvote_path(:postid_from_page => p.id, :userid_from_page => current_user.id) %></b>
              <% else %>
                  <b><%= " #{Vote.find_all_by_post_id(p.id).count} Votes" %></b>
              <% end %>
            </div>

            <div class="post_content" >
              <%=  p.content %>
            </div>

            <div class = "author_time">
              :: Posted by<b> <%= User.find(p.user_id).name %></b>,
              <%= time_ago_in_words(p.created_at) %> ago.
            </div>
            <br />

            <% if current_user.account_type != "guest" %>
                <% if current_user.account_type == "admin" || current_user.id == p.user_id %>
                    <%= link_to "Delete", removepost_path(:post_id => p.id), :class => "post_button_delete round"%>
                    <%= link_to "Reply", newreply_path(:parentid => p.id), :class => "post_button_reply round"%>
                <% else %>
                    <%= link_to "Reply", newreply_path(:parentid => p.id), :class => "post_button_reply_no_delete round"%>
                <% end %>
            <% end %>
          </div>
          <br/>


          <% if replies = Post.find_all_by_parent(p.id, :order => 'posts.created_at ASC')  %>
          <% end %>

          <% if replies.count != 0 %>
              <b>Responses:</b>
          <% end %>

          <% replies.each do |reply| %>
              <div class="c5">

                <div class = "votes vc2" >
                  <% if current_user.account_type != "guest" %>

                      <b> <%= link_to" #{Vote.find_all_by_post_id(reply.id).count} Votes",
                                     newvote_path(:postid_from_page => reply.id, :userid_from_page => current_user.id) %></b>
                  <% else %>
                      <b><%= " #{Vote.find_all_by_post_id(reply.id).count} Votes" %></b>
                  <% end %>
                </div>

                <div class="post_content">
                  <%= reply.content %>
                </div>
                <div class = "author_time">

                  :: Posted by <b><%= User.find(reply.user_id).name %></b>,
                  <%= time_ago_in_words(p.created_at) %> ago.
                </div>

                <br />

                <% if current_user.account_type != "guest" %>
                    <% if current_user.account_type == "admin" || current_user.id == reply.user_id %>
                        <%= link_to "Delete", removepost_path(:post_id => reply.id), :class =>"reply_button_delete round"  %>
                    <% end %>
                <% end %>
              </div>
              &nbsp;

          <% end %>
        </div>
        <br />

    <% end %>
<% end %>

app/views/posts/new.html.erb
<% if current_user.nil? %>
    <div class="flash error">You do not have permissions to access this page!</div>
    <%= link_to "Back to Homepage", root_path %>
<% elsif current_user.account_type == "guest" %>
    <div class="flash error">You do not have permissions to access this page!</div>
    <%= link_to "Back to Posts Homepage", posts_path %>
<% else %>

    <% if @parent_id==-1 %>
        <h1>Submit a new Post</h1>
        <% type = "Post" %>
    <% else %>
        <h1>Write a Reply to Post: </h1>
          <div class="post_content c5">
            <%= Post.find(@parent_id).content %>
            <%= %>
          </div>


        <% type = "Reply" %>
    <% end %>
    <br />

    <%= form_for(:post, :url => posts_path) do |f| %>
        <div class="field">
          <%= render 'shared/error_messages', :object => f.object %>
          <%= hidden_field_tag :parentid, @parent_id  %>
          <%= f.text_area :content, :class => "reply_area" %>
        </div>

        <div class="actions">
          <%= f.submit "Submit #{type}", :class => "submit_post" %>
        </div>
        <%= link_to "Cancel", posts_path, :class => "cancel round" %>
    <% end %>
<% end %>

app/views/posts/searchresult.html.erb
<% if @post_threads.length == 0 && @reply_threads.length == 0 %>
    <p>Sorry, no results found.</p>
<% end %>

<% if @post_threads.length > 0 %>


    <% if @search_type == "user" %>
        <h3><p><%= "All Posts authored by #{@author.name.capitalize}" %></p></h3>
    <% else %>
        <h3><p><%= "All Posts containing searched string: \'#{@search_string}\'" %></p></h3>
    <% end %>

    <% @post_threads.each do |p| %>
        <div class="c6 round">
          <div class="c4">
            <div class = "votes vc1" >
              <% if current_user.account_type != "guest" %>

                  <b> <%= link_to" #{Vote.find_all_by_post_id(p.id).count} Votes",
                                 newvote_path(:postid_from_page => p.id, :userid_from_page => current_user.id) %></b>
              <% else %>
                  <b><%= " #{Vote.find_all_by_post_id(p.id).count} Votes" %></b>
              <% end %>

            </div>

            <div class="post_content">
              <%= p.content %>
            </div>

            <div class = "author_time">
              :: Posted by<b> <%= User.find(p.user_id).name %></b>,
              <%= time_ago_in_words(p.created_at) %> ago.
            </div>

            <br />
            <% if current_user.account_type != "guest" %>
                <% if current_user.account_type == "admin" || current_user.id == p.user_id %>
                    <%= link_to "Delete", removepost_path(:post_id => p.id), :class =>"post_button_delete round" %>
                    <%= link_to "Reply", newreply_path(:parentid => p.id), :class => "post_button_reply round"%>
                <% else %>
                    <%= link_to "Reply", newreply_path(:parentid => p.id), :class =>"post_button_reply_no_delete round" %>
                <% end %>

            <% end %>
          </div>
          <br/>

          <% if replies = Post.find_all_by_parent(p.id, :order => 'posts.created_at ASC')  %>
          <% end %>

          <% if replies.count != 0 %>
              <b>Responses:</b>
          <% end %>
          <% replies.each do |reply| %>
              <div class="c5">

                <div class = "votes vc2" >
                  <% if current_user.account_type != "guest" %>

                      <b> <%= link_to" #{Vote.find_all_by_post_id(reply.id).count} Votes",
                                     newvote_path(:postid_from_page => reply.id, :userid_from_page => current_user.id) %></b>
                  <% else %>
                      <b><%= " #{Vote.find_all_by_post_id(reply.id).count} Votes" %></b>
                  <% end %>
                </div>

                <div class="post_content">
                  <%= reply.content %>
                </div>
                <div class = "author_time">
                  :: Posted by<b> <%= User.find(reply.user_id).name %></b>,
                  <%= time_ago_in_words(reply.created_at) %> ago.
                </div>
                <br/>

                <% if current_user.account_type != "guest" %>
                    <% if current_user.account_type == "admin" || current_user.id == reply.user_id %>
                        <%= link_to "Delete", removepost_path(:post_id => reply.id), :class =>"reply_button_delete round" %>
                    <% end %>
                <% end %>
              </div>
              &nbsp;
          <% end %>
        </div>
        <br />

    <% end %>
<% end %>

<% if @searched_from != "admin_console" %>

    <% if @reply_threads.length > 0 %>
        <% if @search_type == "user" %>
            <h3><p><%= "All Threads containing Replies authored by #{@author.name.capitalize}" %></p></h3>
        <% else %>
            <h3><p><%= "All Threads containing Replies having searched string: \'#{@search_string}\' " %></p></h3>
        <% end %>


        <% @reply_threads.each do |post_number| %>

            <% if p = Post.find(post_number) %>
            <% end %>

            <div class="c6  round">
              <div class="c4">
                <div class = "votes vc1" >
                  <% if current_user.account_type != "guest" %>

                      <b> <%= link_to" #{Vote.find_all_by_post_id(p.id).count} Votes",
                                     newvote_path(:postid_from_page => p.id, :userid_from_page => current_user.id) %></b>
                  <% else %>
                      <b><%= " #{Vote.find_all_by_post_id(p.id).count} Votes" %></b>
                  <% end %>

                </div>

                <div class="post_content">
                  <%= p.content %>
                </div>

                <div class = "author_time">
                  :: Posted by<b> <%= User.find(p.user_id).name %></b>,
                  <%= time_ago_in_words(p.created_at) %> ago.
                </div>

                <br />
                <% if current_user.account_type != "guest" %>
                    <% if current_user.account_type == "admin" || current_user.id == p.user_id %>
                        <%= link_to "Delete", removepost_path(:post_id => p.id), :class =>"post_button_delete round" %>
                        <%= link_to "Reply", newreply_path(:parentid => p.id), :class => "post_button_reply round"%>

                    <% else %>
                        <%= link_to "Reply", newreply_path(:parentid => p.id), :class =>"post_button_reply_no_delete round" %>
                    <% end %>

                <% end %>
              </div>
              <br/>

              <% if replies = Post.find_all_by_parent(p.id, :order => 'posts.created_at ASC')  %>
              <% end %>

              <% if replies.count != 0 %>
                  <b>Responses:</b>
              <% end %>
              <% replies.each do |reply| %>
                  <div class="c5">

                    <div class = "votes vc2" >
                      <% if current_user.account_type != "guest" %>

                          <b> <%= link_to" #{Vote.find_all_by_post_id(reply.id).count} Votes",
                                         newvote_path(:postid_from_page => reply.id, :userid_from_page => current_user.id) %></b>
                      <% else %>
                          <b><%= " #{Vote.find_all_by_post_id(reply.id).count} Votes" %></b>
                      <% end %>
                    </div>

                    <div class="post_content">
                      <%= reply.content %>
                    </div>
                    <div class = "author_time">
                      :: Posted by<b> <%= User.find(reply.user_id).name %></b>,
                      <%= time_ago_in_words(reply.created_at) %> ago.
                    </div>
                    <br/>

                    <% if current_user.account_type != "guest" %>
                        <% if current_user.account_type == "admin" || current_user.id == reply.user_id %>
                            <%= link_to "Delete", removepost_path(:post_id => reply.id), :class =>"reply_button_delete round" %>
                        <% end %>
                    <% end %>
                  </div>
                  &nbsp;
              <% end %>
            </div>
            <br />

        <% end %>
    <% end %>
<% end %>

<br />
<br />

<%= link_to "Back to All Posts", posts_path, :class => "posts_cancel round" %>
<% if @searched_from == "admin_console" %>
    <%= link_to " Back to Manage Accounts", users_path, :class => "accounts_cancel round" %>
<% end %>