config/routes.rb
BackChannelV1::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy, :index]
  resources :posts#, :only => [:new, :create]

  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/newreply', :to => 'posts#newreply'
  match '/showvote', :to => 'votes#show'
  match '/newvote',  :to => 'votes#new'
  match '/removepost',  :to => 'posts#delete'
  match '/newadmin',    :to => 'users#newadmin'
  match '/removeuser',  :to => 'users#delete'
  match '/search',      :to => 'posts#search'
  match '/help',        :to => 'pages#help'

  root :to => 'sessions#new'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

  <% logo = image_tag("backchannel_logo2.png", :alt => "BackChannel App V 1.0", :class => "round") %>
  <% if signed_in? %>
      <%= link_to logo, posts_path %>
  <% else %>
      <%= link_to logo, root_path %>
  <% end %>


  <nav class="round">
    <div>
      <% if !current_user.nil? %>
        <p class="welcome">Welcome <%= current_user.name.capitalize %>!</p>
      <% end %>
    </div>

    <ul>
      <% if signed_in? %>
        <li><%= link_to "Home", posts_path %></li>
      <% end %>

      <% if signed_in? %>
        <% if current_user.account_type == "admin" %>
          <li><%= link_to "Manage Accounts", users_path %></li>
        <% end %>
      <% end %>


      <li><%= link_to "Help", sessions_path %></li>

      <% if signed_in? %>
        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>
  </head>
  <body>
    <div class="container">

      <%= render 'layouts/header' %>

      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>

    </div>
  </body>
</html>